// packages/sample/vue-app/src/App.vue
<script setup lang="ts">
import '@dsy/base/base.css';
import '@dsy/button';
import '@dsy/input';
import { ref } from 'vue';

const name = ref<string>('John Doe');
const count = ref<number>(0);

const increaseCounter = () => {
  count.value = count.value + 1;
};

const handleInput = (e: CustomEvent) => {
  name.value = e.detail.value;
};
</script>

<template>
  <h1>{{ name }} has {{ count }} click</h1>
  <dsy-input type="text" :value="name" @input="handleInput" />
  <div>
    <dsy-button @click="increaseCounter">Click me</dsy-button>
    <dsy-button level="secondary" @click="increaseCounter">Click me otherwise</dsy-button>
  </div>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// packages/sample/react-app/src/App.tsx
import {useEffect, useRef, useState} from 'react'
import './App.css'
import '@dsy/base/base.css';
import '@dsy/button'
import '@dsy/input'

function App() {
  const [count, setCount] = useState(0);
  const [name, setName] = useState('John Doe');
  const increaseCounter = () => setCount(count+1)

  const input = useRef<HTMLElement>();

  useEffect(() => {
    if (input.current) {
      input.current.addEventListener('input', handleInput)
    }

    return () => {
      input.current?.removeEventListener('input', handleInput)
    }
  }, [input])

  const handleInput = (e: Event) => {
    setName((e as CustomEvent).detail.value);
  }

  return (
    <div className="App">
      <header className="App-header">
        <h1>
          {name} has {count} click
        </h1>
        <dsy-input type="text" value={`${name}`} ref={input}/>
        <div>
          <dsy-button onClick={increaseCounter}>Click me</dsy-button>
          <dsy-button level="secondary" onClick={increaseCounter}>Click me otherwise</dsy-button>
        </div>
      </header>
    </div>
  )
}

export default App
